version: '3.3'
services:
  prod:
    container_name: notification_service
    image: notification-service:1.0.0
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
       - MONGO_CONNECTION_URI=mongodb://mongodb:27017/notificationdb
       - REDIS_HOST=redis
    ports:
      - 4002:4002
      - 3001:9229
    networks:
      - notification-service-network
    depends_on:
      - mongodb
      - redis
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
  mongodb:
    image : mongo:latest
    container_name: mongodb
    command: ["mongod"]
    ports:
      - 27017:27017
    networks:
      - notification-service-network
    restart: always
  redis:
    container_name: redis
    image: 'redis:alpine'
    ports:
      - 6379:6379
    networks:
      - notification-service-network
networks:
    notification-service-network:
      driver: bridge